function makeScreens(entries) {
  return entries.map((entry, index) => {
    const [name, detail, groundY] = Array.isArray(entry) ? entry : [entry, "", 464];
    return { name, detail, difficulty: 1 + index * 0.12, pipeCount: Math.min(8, 3 + Math.floor((index + 1) * 0.6)), groundY: groundY || 464 };
  });
}
const scenarios = [
  {
    id: "astigarraga",
    name: "Astigarraga",
    title: "Sagardotegi en alerta",
    sky: "#173b2c",
    ground: "#2e2117",
    water: "#b9833b",
    landmark: "#6f4422",
    floodMod: 0.94,
    leakMod: 0.96,
    dropSpeedMod: 0.96,
    map: { center: [43.2815684, -1.9474769], zoom: 15, drift: [0.010, 0.024] },
    pipeY: [98, 132, 92, 128, 102, 136],
    screens: makeScreens([
      ["Entrada de Ergobia", "Primeras fugas junto al camino hacia Astigarraga."],
      ["Sagardoetxea", "La presión sube entre depósitos y carteles de sidra."],
      ["Plaza del Pueblo", "Tuberías cruzadas bajo los soportales."],
      ["Bidebitarte", "Pasillos estrechos y escapes más altos."],
      ["Camino de Petritegi", "Barriles y curvas complican el acceso."],
      ["Murgia", "La red vieja empieza a temblar."],
      ["Santiagomendi", "La cuesta exige mejores saltos.", 444],
      ["Ribera del Urumea", "El agua exterior empuja la inundación.", 484],
      ["Zona de Sidrerías", "Muchas fugas pequeñas a la vez."],
      ["Gran Txotx Final", "Última sala con presión máxima."]
    ]),
    notes: ["10 pantallas con detalles locales", "Inundación algo más tranquila", "Tuberías bajas y reparables"]
  },
  {
    id: "pasai-antxo",
    name: "Pasai Antxo",
    title: "Muelle bajo presión",
    sky: "#10304a",
    ground: "#17212f",
    water: "#1d7fa8",
    landmark: "#c46f38",
    floodMod: 1.14,
    leakMod: 1.12,
    dropSpeedMod: 1.16,
    map: { center: [43.3171948, -1.9179836], zoom: 16, drift: [0.006, 0.018] },
    pipeY: [76, 120, 84, 126, 78, 118],
    screens: makeScreens([
      ["Pasai Antxo Renfe", "Arranque junto a la estación y Nafarroa etorbidea."],
      ["Nafarroa Etorbidea", "El tráfico vibra sobre las conducciones."],
      ["Muelle Interior", "Gotas rápidas por la humedad del puerto.", 484],
      ["Grúas del Puerto", "Tuberías altas y escapes verticales.", 444],
      ["Molinao", "La canalización se estrecha cerca del agua."],
      ["Entrada a la Bahía", "Oleaje y presión lateral."],
      ["Tinglados", "Sombras, cajas y fugas simultáneas."],
      ["Vías y Pasarela", "Reparaciones rápidas entre estructuras."],
      ["Dársena de Antxo", "La pantalla más húmeda antes del final."],
      ["Alarma Portuaria", "Todo el muelle pierde agua a la vez."]
    ]),
    notes: ["10 pantallas con ambiente portuario", "Más fugas y gotas más rápidas", "Partida más intensa"]
  },
  {
    id: "larratxo-altza",
    name: "Larratxo / Altza",
    title: "Cuestas y bloques",
    sky: "#271a3d",
    ground: "#22293d",
    water: "#4c72d9",
    landmark: "#5b6478",
    floodMod: 1.04,
    leakMod: 1,
    dropSpeedMod: 1.04,
    map: { center: [43.3141417, -1.9390155], zoom: 16, drift: [0.006, 0.018] },
    pipeY: [138, 82, 146, 90, 132, 78],
    screens: makeScreens([
      ["Larratxo Parkea", "Inicio entre árboles y bloques altos."],
      ["Txirrita Bertsolaria", "Tuberías siguiendo el paseo."],
      ["Estación de Larratxo", "Fugas cerca del acceso ferroviario."],
      ["Altza Plaza", "La red se reparte bajo el barrio."],
      ["Casares", "Conductos altos y saltos precisos."],
      ["Leosiñeta", "Pantalla de desniveles y escapes bajos."],
      ["Arriaga", "La presión se concentra en columnas."],
      ["Cuestas de Altza", "Tuberías desalineadas por la pendiente.", 444],
      ["Buenavista", "Bloques densos y poca ventana de reacción.", 448],
      ["Altza Final", "Todas las alturas entran en juego."]
    ]),
    notes: ["10 pantallas con cuestas y bloques", "Tuberías a distintas alturas", "Dificultad irregular"]
  },
  {
    id: "intxaurrondo",
    name: "Intxaurrondo",
    title: "Avería en la estación",
    sky: "#20334f",
    ground: "#263548",
    water: "#39b6c8",
    landmark: "#8792a8",
    floodMod: 1.08,
    leakMod: 1.06,
    dropSpeedMod: 1.1,
    map: { center: [43.3141100, -1.9531242], zoom: 16, drift: [0.006, 0.018] },
    pipeY: [110, 86, 126, 92, 140, 78],
    screens: makeScreens([
      ["Intxaurrondo Hegoa", "Primer tramo del barrio con tuberías medias."],
      ["Estación de Intxaurrondo", "La vibración de las vías acelera las gotas."],
      ["Paseo del Topo", "Fugas en línea bajo la pasarela."],
      ["Sagastieder", "Bloques compactos y poco espacio."],
      ["Marrutxipi", "Cruce de conducciones antiguas."],
      ["Ategorrieta Bidea", "Pantalla larga con presión creciente."],
      ["Hego Intxaurrondo", "Fugas alternas arriba y abajo."],
      ["Ekialdea", "La red del este se descompensa."],
      ["Túnel Técnico", "Gotas muy rápidas desde el techo."],
      ["Central de Barrio", "Cierre final de la avería general."]
    ]),
    notes: ["Nuevo escenario de 10 pantallas", "Inspirado en estación y barrio", "Dificultad media-alta"]
  },
  {
    id: "egia",
    name: "Egia",
    title: "Avería junto al Urumea",
    sky: "#26324f",
    ground: "#2f2633",
    water: "#5cc7e8",
    landmark: "#c26f42",
    floodMod: 1.1,
    leakMod: 1.08,
    dropSpeedMod: 1.08,
    map: { center: [43.3173500, -1.9771000], zoom: 16, drift: [0.006, 0.018] },
    pipeY: [124, 88, 136, 96, 118, 78],
    screens: makeScreens([
      ["Tabakalera", "La antigua fábrica cultural vibra con tuberías altas."],
      ["Cristina Enea", "El parque suaviza el terreno, pero hay fugas ocultas."],
      ["Puente de Mundaiz", "El Urumea empuja el nivel del agua desde abajo."],
      ["Duque de Mandas", "Pantalla urbana con conducciones cruzadas."],
      ["Estación del Norte", "Las vías hacen temblar los empalmes."],
      ["Atotxa", "Zona densa con escapes simultáneos."],
      ["Ametzagaña", "Pendiente y tuberías desalineadas."],
      ["Mundaiz Ikastetxea", "Fugas medianas repartidas por todo el tramo."],
      ["Ribera de Egia", "El río acelera la inundación si te retrasas.", 484],
      ["Egia Final", "Último corte de agua antes de salvar el barrio."]
    ]),
    notes: ["Nuevo barrio con 10 pantallas", "Tabakalera, Urumea y Cristina Enea", "Dificultad media-alta"]
  },
  {
    id: "gros",
    name: "Gros",
    title: "Oleaje en Zurriola",
    sky: "#163852",
    ground: "#273244",
    water: "#49c7ee",
    landmark: "#e0c27a",
    floodMod: 1.16,
    leakMod: 1.1,
    dropSpeedMod: 1.12,
    map: { center: [43.3224000, -1.9730000], zoom: 16, drift: [0.006, 0.018] },
    pipeY: [92, 124, 80, 134, 104, 146],
    screens: makeScreens([
      ["Zurriola", "El oleaje empuja el agua hacia la red.", 484],
      ["Kursaal", "Cristales y tuberías bajo presión.", 448],
      ["Plaza Cataluña", "Averías repartidas por el centro de Gros."],
      ["Usandizaga", "Calles estrechas y escapes rápidos."],
      ["Secundino Esnaola", "El barrio vibra con fugas cruzadas."],
      ["Nafarroa Behera", "Tramo largo con enemigos patrullando."],
      ["Sagues", "La brisa seca algo, pero las fugas son fuertes."],
      ["Ategorrieta", "Conexión hacia la zona este."],
      ["Paseo de Colón", "Averías urbanas encadenadas."],
      ["Gros Final", "Última emergencia junto a la playa."]
    ]),
    notes: ["Zurriola, Kursaal y Sagues", "Agua rápida", "Dificultad alta"]
  },
  {
    id: "amara",
    name: "Amara",
    title: "Avería en Anoeta",
    sky: "#283247",
    ground: "#30313b",
    water: "#69a7ff",
    landmark: "#5fbf72",
    floodMod: 1.05,
    leakMod: 1.04,
    dropSpeedMod: 1.04,
    map: { center: [43.3059000, -1.9806000], zoom: 15, drift: [0.007, 0.020] },
    pipeY: [118, 96, 138, 84, 126, 104],
    screens: makeScreens([
      ["Anoeta", "La presión sube bajo el estadio."],
      ["Madrid Hiribidea", "Avenida amplia con fugas separadas."],
      ["Pío XII", "Nudo de tuberías y tráfico."],
      ["Morlans", "Zona técnica con escapes bajos."],
      ["Arcco", "Pantalla comercial con puertas averiadas."],
      ["Easo", "Conexión hacia el centro."],
      ["Sancho el Sabio", "Línea recta llena de averías."],
      ["Riberas", "El agua vuelve por el río."],
      ["Loiola Bidea", "Pantalla de transición dura."],
      ["Amara Final", "Cierre general del colector."]
    ]),
    notes: ["Anoeta, Pío XII y Riberas", "Dificultad equilibrada", "Mapa amplio"]
  },
  {
    id: "parte-vieja",
    name: "Parte Vieja",
    title: "Calles estrechas",
    sky: "#332238",
    ground: "#30272a",
    water: "#3fbdd7",
    landmark: "#d48f4a",
    floodMod: 1.2,
    leakMod: 1.16,
    dropSpeedMod: 1.08,
    map: { center: [43.3231000, -1.9869000], zoom: 17, drift: [0.004, 0.012] },
    pipeY: [78, 112, 88, 132, 96, 144],
    screens: makeScreens([
      ["Boulevard", "Entrada con mucho tránsito."],
      ["31 de Agosto", "Tuberías antiguas y estrechas."],
      ["Plaza Constitución", "Averías alrededor de soportales."],
      ["Puerto", "El agua salada complica el drenaje.", 480],
      ["San Vicente", "Fugas altas entre fachadas.", 448],
      ["Santa María", "Conductos viejos y baja visibilidad."],
      ["Fermín Calbetón", "Zona densa con enemigos cercanos."],
      ["Narrika", "Pantalla corta pero intensa."],
      ["Kaia", "El puerto vuelve a empujar agua."],
      ["Parte Vieja Final", "Última reparación entre calles antiguas."]
    ]),
    notes: ["Calles estrechas y puerto", "Dificultad muy alta", "Fugas antiguas"]
  }
];
